In [1]:
import torch
import numpy as np

## 1. 基于内容创建tensor

In [2]:
# 传入标量
t1 = torch.tensor(10)
print(t1)
print(t1.shape)

tensor(10)
torch.Size([])


In [3]:
# 传入列表 向量
t1 = torch.tensor([10, 20, 30])
print(t1)
print(t1.shape)

tensor([10, 20, 30])
torch.Size([3])


In [4]:
# 传入一个二维的列表(矩阵)
t1 = torch.tensor([[10, 20, 30], [40, 50, 60]])
print(t1)
print(t1.shape)

tensor([[10, 20, 30],
        [40, 50, 60]])
torch.Size([2, 3])


In [5]:
# 传入一个3维的列表(张量)
t1 = torch.tensor([ [[10, 20, 30], [40, 50, 60]],   [[10, 20, 30], [40, 50, 60]]])
print(t1)
print(t1.shape)

tensor([[[10, 20, 30],
         [40, 50, 60]],

        [[10, 20, 30],
         [40, 50, 60]]])
torch.Size([2, 2, 3])


In [12]:
t1 = torch.tensor(np.array([[10.0, 20, 30], [40, 50, 60]]))
print(t1)
print(t1.shape)

tensor([[10., 20., 30.],
        [40., 50., 60.]], dtype=torch.float64)
torch.Size([2, 3])


In [13]:
# 查看数据类型
print(t1.dtype)

torch.float64


## 2. 基于形状创建tensor

In [14]:
t1 = torch.Tensor(2,3, 5)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])
torch.Size([2, 3, 5])
torch.float32


In [ ]:
# 3. 数据类型: 基于内容(tensor), 遵守内容的类型 基于形状(Tensor), 默认float32

# 3. 创建指定类型的张量

In [16]:
t1 = torch.tensor([[10, 20, 30], [40, 50, 60]], dtype=torch.float64)
print(t1.dtype)

torch.float64


In [19]:
t1 = torch.tensor([[10, 20, 30], [40, 50, 60]]).to(torch.float64)
print(t1.dtype)


torch.float64
torch.float64


In [22]:
t1 = torch.IntTensor(2, 3)
print(t1.dtype)

torch.int32


In [23]:
t1 = torch.LongTensor(2, 3)
print(t1.dtype)

torch.int64


In [24]:
t1 = torch.FloatTensor(2, 3)
print(t1.dtype)

torch.float32


In [25]:
t1 = torch.DoubleTensor(2, 3)
print(t1.dtype)

torch.float64


In [26]:
t1 = torch.HalfTensor(2, 3)
print(t1.dtype)

torch.float16


In [27]:
t1 = torch.ShortTensor(2, 3)
print(t1.dtype)

torch.int16


In [28]:
t1 = torch.ByteTensor(2, 3)
print(t1.dtype)

torch.uint8


In [29]:
t1 = torch.BoolTensor(2, 3)
print(t1.dtype)

torch.bool


# 4. 指定区间创建张量

In [31]:
t1 = torch.arange(10)  # start=0 end=10 step=1  [start, end)
print(t1)

t1 = torch.arange(start=10, end=100, step=5)  # start=0 end=10 step=1  [start, end)
print(t1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])


In [32]:
t1 = torch.linspace(1, 10, 3)  # 步长会自动计算: (end-start)/(steps-1)   [start, end]
print(t1)

tensor([ 1.0000,  5.5000, 10.0000])


In [34]:
t1 = torch.logspace(1, 3, 3, base=torch.e)  # 10^1  10^2
print(t1)

tensor([ 2.7183,  7.3891, 20.0855])


## 5. 根据填充创建张量

In [35]:
t1 = torch.ones(2,3)
print(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [36]:
t2 = torch.ones_like(t1)
print(t2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [37]:
t1 = torch.zeros(2,3)
print(t1)
t2 = torch.zeros_like(t1)
print(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [48]:
t1 = torch.empty(2,3)
print(t1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [49]:
t1 = torch.full( (2,3), 10)
print(t1)

tensor([[10, 10, 10],
        [10, 10, 10]])


In [53]:
t1 = torch.eye(5)
print(t1)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


# 6. 随机创建张量

In [63]:
t1 = torch.rand(2, 3)  # 均匀分布: [0,1]
print(t1)

tensor([[0.3385, 0.0968, 0.0170],
        [0.6110, 0.3940, 0.7554]])


In [73]:
t1 = torch.randint(low=10, high=100, size=(2,3))  # 均匀分布
print(t1)

tensor([[83, 52, 29],
        [55, 73, 84]])


In [84]:
# 标准正态分布
t1 = torch.randn(2, 3)
print(t1)

tensor([[ 0.6308, -0.8295, -0.1718],
        [ 2.0143, -0.2601,  1.5477]])


In [94]:
t1 = torch.normal(mean=5, std=3, size=(2,3))
print(t1)

tensor([[ 9.7985,  6.8761,  5.7490],
        [10.8609, 10.6083,  3.6357]])


In [106]:
# 洗牌(打乱)
t1 = torch.randperm(10)  # [0, 10)
print(t1)

tensor([3, 1, 9, 8, 0, 5, 4, 2, 6, 7])


In [121]:
# 查看随机数种子
print(torch.random.initial_seed())

42


In [120]:
# 设置随机数种子
torch.random.manual_seed(42)