In [1]:
import torch

## 1. 元素类型的转换

In [2]:
t1 = torch.tensor([1,2,3])
print(t1.dtype)

torch.int64


In [3]:
# 使用type方法
t2 = t1.type(torch.float32)
print(t2.dtype)

torch.float32


In [4]:
# to 方法
t2 = t1.to(torch.float32)
print(t2.dtype)

torch.float32


In [6]:
# 直接调用类型方法
t2 = t1.float()
print(t2.dtype)
t2 = t1.long()
print(t2.dtype)

torch.float32
torch.int64


## tensor =>  ndarray

In [7]:
import numpy as np

In [8]:
t1 = torch.tensor([1,2,3])

In [10]:
n1 = t1.numpy()
print(type(n1))
print(n1)

<class 'numpy.ndarray'>
[1 2 3]


In [11]:
# 内存的问题: 内存共享
t1[0] = 10
print(t1)
print(n1)

tensor([10,  2,  3])
[10  2  3]


In [12]:
n2 = t1.numpy().copy()
print(n2)
t1[0] = 100
print(n2)

[10  2  3]
[10  2  3]


## ndarray => numpy

In [13]:
n1 = np.array([1,2,3])

In [14]:
t1 = torch.from_numpy(n1)
print(t1)

tensor([1, 2, 3])


In [15]:
n1[0] = 100
print(n1)
print(t1)

[100   2   3]
tensor([100,   2,   3])


In [16]:
t2 = torch.from_numpy(n1).clone()
print(t2)
n1[0] = 200
print(n1)
print(t2)

tensor([100,   2,   3])
[200   2   3]
tensor([100,   2,   3])


# 张量=>标量

In [19]:
t1 = torch.tensor([[[10]]])  # tensor只有一个元素的时候,可以转 维度可以无限
print(t1.item())

10
