In [1]:
from xml.sax.handler import property_interning_dict

import torch

## 1. 基本运算

In [2]:
t1 = torch.tensor([[1, 2, 3], [10, 20, 30]])

In [5]:
print(t1 + 10)
print(t1)
t1.add_(10)
print(t1)

tensor([[11, 12, 13],
        [20, 30, 40]])
tensor([[ 1,  2,  3],
        [10, 20, 30]])
tensor([[11, 12, 13],
        [20, 30, 40]])


## 2. 元素级运算(张量和张量)

In [11]:
t1 = torch.tensor([[1, 2, 3], [10, 20, 30]])
t2 = torch.tensor([[100, 200, 300], [5, 6, 7]])
t3 = torch.tensor([[100], [5]])

In [12]:
# 张量 + 张量  形状一样, 或者满足广播条件
print(t1 + t2)
print(t1 + t3)

tensor([[101, 202, 303],
        [ 15,  26,  37]])
tensor([[101, 102, 103],
        [ 15,  25,  35]])


In [13]:
# 张量 * 张量  对位相差  哈达玛积
print(t1 * t2)

tensor([[100, 400, 900],
        [ 50, 120, 210]])


## 3. 矩阵相乘

In [16]:
t1 = torch.tensor([[1, 2, 3], [10, 20, 30]])
t2 = torch.tensor([[100, 200, 300], [5, 6, 7], [7, 8, 9]])

In [17]:
print(t1 @ t2)

tensor([[ 131,  236,  341],
        [1310, 2360, 3410]])


In [18]:
print(t1.mm(t2))  # 只能用于矩阵, 维数超过2就不支持

tensor([[ 131,  236,  341],
        [1310, 2360, 3410]])


In [19]:
print(t1.matmul(t2))


tensor([[ 131,  236,  341],
        [1310, 2360, 3410]])


In [21]:
t1 = torch.tensor([[[1, 2, 3], [4, 5, 6], [6, 5, 4]], [[3, 2, 1], [3, 2, 1], [3, 2, 1]]])
t2 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[6, 5], [4, 3], [2, 1]]])
print(t1.shape)
print(t2.shape)

torch.Size([2, 3, 3])
torch.Size([2, 3, 2])


In [22]:
print(t1 @ t2)

tensor([[[22, 28],
         [49, 64],
         [41, 56]],

        [[28, 22],
         [28, 22],
         [28, 22]]])


In [23]:
# print(t1.mm(t2)) # mm不支持高纬张量

RuntimeError: self must be a matrix