In [1]:
import torch

In [9]:
t1 = torch.randint(1, 10, (2, 3, 4)).float()
print(t1)

tensor([[[6., 7., 1., 1.],
         [2., 4., 3., 6.],
         [7., 2., 3., 1.]],

        [[9., 7., 8., 6.],
         [5., 9., 2., 3.],
         [2., 4., 1., 2.]]])


In [4]:
print(t1.sum())

tensor(134)


In [5]:
print(t1.sum(dim=0))

tensor([[ 5, 13, 17,  6],
        [12, 17, 12, 11],
        [15,  7, 10,  9]])


In [6]:
print(t1.sum(dim=1))

tensor([[17, 22, 20, 14],
        [15, 15, 19, 12]])


In [7]:
print(t1.sum(dim=2))

tensor([[24, 25, 24],
        [17, 27, 17]])


In [11]:
# mean
print(t1.mean(dim=0))

tensor([[7.5000, 7.0000, 4.5000, 3.5000],
        [3.5000, 6.5000, 2.5000, 4.5000],
        [4.5000, 3.0000, 2.0000, 1.5000]])


In [14]:
print(t1.max())

tensor(9.)


In [15]:
print(t1.max(dim=0))


torch.return_types.max(
values=tensor([[9., 7., 8., 6.],
        [5., 9., 3., 6.],
        [7., 4., 3., 2.]]),
indices=tensor([[1, 0, 1, 1],
        [1, 1, 0, 0],
        [0, 1, 0, 1]]))


In [17]:
print(t1.var())
print(t1.var(dim=0))

tensor(7.1286)
tensor([[ 4.5000,  0.0000, 24.5000, 12.5000],
        [ 4.5000, 12.5000,  0.5000,  4.5000],
        [12.5000,  2.0000,  2.0000,  0.5000]])


In [18]:
print(t1.std())

tensor(2.6699)


In [22]:
print(t1.unique())

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [28]:
print(t1.sort(dim=2))
print(t1.sort())  # 不加dim默认是按照矩阵的行进行排序

torch.return_types.sort(
values=tensor([[[1., 1., 6., 7.],
         [2., 3., 4., 6.],
         [1., 2., 3., 7.]],

        [[6., 7., 8., 9.],
         [2., 3., 5., 9.],
         [1., 2., 2., 4.]]]),
indices=tensor([[[2, 3, 0, 1],
         [0, 2, 1, 3],
         [3, 1, 2, 0]],

        [[3, 1, 2, 0],
         [2, 3, 0, 1],
         [2, 0, 3, 1]]]))
torch.return_types.sort(
values=tensor([[[1., 1., 6., 7.],
         [2., 3., 4., 6.],
         [1., 2., 3., 7.]],

        [[6., 7., 8., 9.],
         [2., 3., 5., 9.],
         [1., 2., 2., 4.]]]),
indices=tensor([[[2, 3, 0, 1],
         [0, 2, 1, 3],
         [3, 1, 2, 0]],

        [[3, 1, 2, 0],
         [2, 3, 0, 1],
         [2, 0, 3, 1]]]))
