In [2]:
import torch
t = torch.randint(0, 10, (2, 5, 4))
print(t)

tensor([[[4, 3, 8, 9],
         [9, 8, 8, 6],
         [4, 0, 7, 9],
         [9, 0, 6, 7],
         [0, 4, 8, 4]],

        [[8, 3, 3, 7],
         [1, 8, 4, 1],
         [1, 4, 2, 8],
         [2, 6, 2, 0],
         [4, 5, 0, 4]]])


## 简单索引

In [3]:
print(t[0][0][0])
print(t[0,0,0])

tensor(4)
tensor(4)


In [4]:
print(t[0])  # 取第一个矩阵

tensor([[4, 3, 8, 9],
        [9, 8, 8, 6],
        [4, 0, 7, 9],
        [9, 0, 6, 7],
        [0, 4, 8, 4]])


In [5]:
print(t[0,0])

tensor([4, 3, 8, 9])


## 范围索引

In [7]:
print(t[1:])

tensor([[[8, 3, 3, 7],
         [1, 8, 4, 1],
         [1, 4, 2, 8],
         [2, 6, 2, 0],
         [4, 5, 0, 4]]])


In [9]:
print(t[1,1:, 2:])

tensor([[4, 1],
        [2, 8],
        [2, 0],
        [0, 4]])


In [10]:
print(t[-2,1:, 2:])

tensor([[8, 6],
        [7, 9],
        [6, 7],
        [8, 4]])


## 列表索引

In [11]:
list1 = [0,1,1]
list2 = [1,3,2]
print(t[list1, list2])


tensor([[9, 8, 8, 6],
        [2, 6, 2, 0],
        [1, 4, 2, 8]])


In [15]:
list1 = [[0], [1]]
list2 = [1,3,2]
print(t[list1, list2])

tensor([[[9, 8, 8, 6],
         [9, 0, 6, 7],
         [4, 0, 7, 9]],

        [[1, 8, 4, 1],
         [2, 6, 2, 0],
         [1, 4, 2, 8]]])


## 布尔索引

In [18]:
#  取出所有大于5的元素
mask = t > 5
mask

tensor([[[False, False,  True,  True],
         [ True,  True,  True,  True],
         [False, False,  True,  True],
         [ True, False,  True,  True],
         [False, False,  True, False]],

        [[ True, False, False,  True],
         [False,  True, False, False],
         [False, False, False,  True],
         [False,  True, False, False],
         [False, False, False, False]]])

In [19]:
print(t[mask])

tensor([8, 9, 9, 8, 8, 6, 7, 9, 9, 6, 7, 8, 8, 7, 8, 8, 6])


In [22]:
# 取出每行的首元素大于5的那些行
mask = t[:, :, 0] > 5
print(mask)

print(t[mask])

tensor([[False,  True, False,  True, False],
        [ True, False, False, False, False]])
tensor([[9, 8, 8, 6],
        [9, 0, 6, 7],
        [8, 3, 3, 7]])


In [26]:
# 取出每列的首元素大于5的那些列
mask = t[:, 0, :] > 5
print(mask)

tensor([[False, False,  True,  True],
        [ True, False, False,  True]])


In [29]:
print(t.mT[mask].T)

tensor([[8, 9, 8, 7],
        [8, 6, 1, 1],
        [7, 9, 1, 8],
        [6, 7, 2, 0],
        [8, 4, 4, 4]])
