In [1]:
import torch
t = torch.randint(0, 10, (2, 5, 4))
print(t)

tensor([[[7, 3, 7, 2],
         [4, 4, 0, 1],
         [1, 7, 1, 9],
         [0, 8, 1, 5],
         [4, 5, 1, 3]],

        [[7, 4, 3, 2],
         [5, 5, 9, 6],
         [4, 9, 0, 3],
         [3, 6, 1, 8],
         [0, 8, 9, 5]]])


## 维度的变换

In [7]:
print(t.T)  # (0,2,3) => (3,2,0)

tensor([[[7, 7],
         [4, 5],
         [1, 4],
         [0, 3],
         [4, 0]],

        [[3, 4],
         [4, 5],
         [7, 9],
         [8, 6],
         [5, 8]],

        [[7, 3],
         [0, 9],
         [1, 0],
         [1, 1],
         [1, 9]],

        [[2, 2],
         [1, 6],
         [9, 3],
         [5, 8],
         [3, 5]]])


In [8]:
print(t.mT)  # 只转置最后2个维度

tensor([[[7, 4, 1, 0, 4],
         [3, 4, 7, 8, 5],
         [7, 0, 1, 1, 1],
         [2, 1, 9, 5, 3]],

        [[7, 5, 4, 3, 0],
         [4, 5, 9, 6, 8],
         [3, 9, 0, 1, 9],
         [2, 6, 3, 8, 5]]])


In [9]:
# 任意交换两个维度
print(t.transpose(0, 1))

tensor([[[7, 3, 7, 2],
         [7, 4, 3, 2]],

        [[4, 4, 0, 1],
         [5, 5, 9, 6]],

        [[1, 7, 1, 9],
         [4, 9, 0, 3]],

        [[0, 8, 1, 5],
         [3, 6, 1, 8]],

        [[4, 5, 1, 3],
         [0, 8, 9, 5]]])


In [12]:
# 重新排列所有维度
print(t.permute(0, 2,1))
print(t.permute(2, 0, 1).shape)

tensor([[[7, 4, 1, 0, 4],
         [3, 4, 7, 8, 5],
         [7, 0, 1, 1, 1],
         [2, 1, 9, 5, 3]],

        [[7, 5, 4, 3, 0],
         [4, 5, 9, 6, 8],
         [3, 9, 0, 1, 9],
         [2, 6, 3, 8, 5]]])
torch.Size([4, 2, 5])


## 形状调整

In [21]:
t1 = t.reshape(1, -1)
print(t1)
print(t1.shape)


tensor([[7, 3, 7, 2, 4, 4, 0, 1, 1, 7, 1, 9, 0, 8, 1, 5, 4, 5, 1, 3, 7, 4, 3, 2,
         5, 5, 9, 6, 4, 9, 0, 3, 3, 6, 1, 8, 0, 8, 9, 5]])
torch.Size([1, 40])


In [24]:
t1 = t.reshape(1,1,1,2,-1)
print(t1)
print(t1.shape)

tensor([[[[[7, 3, 7, 2, 4, 4, 0, 1, 1, 7, 1, 9, 0, 8, 1, 5, 4, 5, 1, 3],
           [7, 4, 3, 2, 5, 5, 9, 6, 4, 9, 0, 3, 3, 6, 1, 8, 0, 8, 9, 5]]]]])
torch.Size([1, 1, 1, 2, 20])


In [30]:
# view
print(t1.view(1,-1))

t2 = t1.mT
print(t1.is_contiguous())
print(t2.is_contiguous())
# contiguous 强制内存连续. 一般推荐使用reshape
print(t2.contiguous().view(1,-1))

tensor([[7, 3, 7, 2, 4, 4, 0, 1, 1, 7, 1, 9, 0, 8, 1, 5, 4, 5, 1, 3, 7, 4, 3, 2,
         5, 5, 9, 6, 4, 9, 0, 3, 3, 6, 1, 8, 0, 8, 9, 5]])
True
False
tensor([[7, 7, 3, 4, 7, 3, 2, 2, 4, 5, 4, 5, 0, 9, 1, 6, 1, 4, 7, 9, 1, 0, 9, 3,
         0, 3, 8, 6, 1, 1, 5, 8, 4, 0, 5, 8, 1, 9, 3, 5]])


# 增删维度

In [31]:
t1 = torch.randint(1, 10, (2, 4))
print(t1)
print(t1.reshape(2,1, 4))


tensor([[5, 7, 4, 8],
        [4, 6, 4, 2]])
tensor([[[5, 7, 4, 8]],

        [[4, 6, 4, 2]]])


In [37]:
print(t1.unsqueeze(dim=0)) # 增加维度

tensor([[[5, 7, 4, 8],
         [4, 6, 4, 2]]])


In [48]:
t2 = t1.unsqueeze(dim=0).unsqueeze(dim=0).unsqueeze(dim=-1).unsqueeze(dim=-1)
print(t2)
print(t2)
print(t2.shape)

tensor([[[[[[5]],

           [[7]],

           [[4]],

           [[8]]],


          [[[4]],

           [[6]],

           [[4]],

           [[2]]]]]])
tensor([[[[[[5]],

           [[7]],

           [[4]],

           [[8]]],


          [[[4]],

           [[6]],

           [[4]],

           [[2]]]]]])
torch.Size([1, 1, 2, 4, 1, 1])


In [56]:
print(t2.squeeze())

tensor([[5, 7, 4, 8],
        [4, 6, 4, 2]])


## tensor的拼接

In [59]:
t1 = torch.randint(1, 10, (2, 1, 3))
t2 = torch.randint(1, 10, (2, 3, 3))
print(t1)
print(t2)


tensor([[[5, 5, 1]],

        [[8, 5, 9]]])
tensor([[[7, 8, 1],
         [8, 5, 3],
         [5, 9, 3]],

        [[6, 6, 6],
         [7, 8, 9],
         [3, 8, 8]]])


In [62]:
print(torch.cat((t1, t2), dim=1))

tensor([[[5, 5, 1],
         [7, 8, 1],
         [8, 5, 3],
         [5, 9, 3]],

        [[8, 5, 9],
         [6, 6, 6],
         [7, 8, 9],
         [3, 8, 8]]])


In [66]:
# stack
t1 = torch.randint(1, 10, (2, 2, 5))
t2 = torch.randint(1, 10, (2, 2, 5))
print(t1)
print(t2)

tensor([[[9, 7, 4, 4, 7],
         [5, 3, 4, 6, 8]],

        [[3, 9, 3, 8, 5],
         [3, 6, 8, 7, 2]]])
tensor([[[1, 9, 4, 5, 4],
         [9, 2, 5, 5, 2]],

        [[5, 3, 4, 7, 9],
         [6, 6, 4, 4, 6]]])


In [70]:
# 等价于: 先unsequze, 然后再cat
t3 = torch.stack((t1, t2), dim=-1)
print(t3)
print(t3.shape)

tensor([[[[9, 1],
          [7, 9],
          [4, 4],
          [4, 5],
          [7, 4]],

         [[5, 9],
          [3, 2],
          [4, 5],
          [6, 5],
          [8, 2]]],


        [[[3, 5],
          [9, 3],
          [3, 4],
          [8, 7],
          [5, 9]],

         [[3, 6],
          [6, 6],
          [8, 4],
          [7, 4],
          [2, 6]]]])
torch.Size([2, 2, 5, 2])
